Mass
spectrometry (MS) has become an indispensable tool for investigating
the architectures and dynamics of macromolecular assemblies. Here
we show that covalent labeling of solvent accessible residues followed
by their MS-based identification yields modeling restraints that allow
mapping the location and orientation of subunits within protein assemblies.
Together with complementary restraints derived from cross-linking
and native MS, we built native-like models of four heterocomplexes
with known subunit structures and compared them with available X-ray
crystal structures. The results demonstrated that covalent labeling
followed by MS markedly increased the predictive power of the integrative
modeling strategy enabling more accurate protein assembly models.
We applied this strategy to the F-type ATP synthase from spinach chloroplasts
(cATPase) providing a structural basis for its function as a nanomotor.
By subjecting the models generated by our restraint-based strategy
to molecular dynamics (MD) simulations, we revealed the conformational
states of the peripheral stalk and assigned flexible regions in the
enzyme. Our strategy can readily incorporate complementary chemical
labeling strategies and we anticipate that it will be applicable to
many other systems providing new insights into the structure and function
of protein complexes.