Metabolic alterations and cardiovascular diseases, such as atherosclerosis, are associated
with lifestyle modifications, particularly the increase of physical inactivity and poor eating habits,
which contribute to one of the main causes of death in modern times. Cardiovascular diseases are
positively correlated with several illnesses, such as obesity, hypertension and dyslipidemia, and these
disorders are known to contribute to changes in immune cells, cytokines and metabolism. Atherosclerosis
is a chronic inflammatory disease characterized by the formation of lipid plaques and fibrous
tissue (atheroma) in the artery walls and this process is related to the oxidation of LDL-c (low density lipoprotein) and the
formation of a particle, termed LDLox, which can generate toxic injury to the vessel wall. In this atherogenic process there
is an inflammatory response generated by the injury in the vascular endothelium, which in itself is able to express and
secrete a variety of molecules, such as myeloid colony-stimulating factors (M-CSF), monocyte chemotactic protein-1
(MCP-1) and tumor necrosis factor alpha (TNF-α), that act as activators of the immune system. Therefore, the main
purpose of this review is to highlight the immuno-metabolic alterations involving the thickening and stiffness of arteries
observed in atherosclerosis, and how chronic exercise can act as an anti-inflammatory and anti-atherogenic approach.
