The
antagonist-bound crystal structure of the nociceptin receptor
(NOP), from the opioid receptor family, was recently reported along
with those of the other opioid receptors bound to opioid antagonists.
We recently reported the first homology model of the ‘active-state’
of the NOP receptor, which when docked with ‘agonist’
ligands showed differences in the TM helices and residues, consistent
with GPCR activation after agonist binding. In this study, we explored
the use of the active-state NOP homology model for structure-based
virtual screening to discover NOP ligands containing new chemical
scaffolds. Several NOP agonist and antagonist ligands previously reported
are based on a common piperidine scaffold. Given the structure–activity
relationships for known NOP ligands, we developed a hybrid method
that combines a structure-based and ligand-based approach, utilizing
the active-state NOP receptor as well as the pharmacophoric features
of known NOP ligands, to identify novel NOP binding scaffolds by virtual
screening. Multiple conformations of the NOP active site including
the flexible second extracellular loop (EL2) loop were generated by
simulated annealing and ranked using enrichment factor (EF) analysis
and a ligand–decoy dataset containing known NOP agonist ligands.
The enrichment factors were further improved by combining shape-based
screening of this ligand–decoy dataset and calculation of consensus
scores. This combined structure-based and ligand-based EF analysis
yielded higher enrichment factors than the individual methods, suggesting
the effectiveness of the hybrid approach. Virtual screening of the
CNS Permeable subset of the ZINC database was carried out using the
above-mentioned hybrid approach in a tiered fashion utilizing a ligand
pharmacophore-based filtering step, followed by structure-based virtual
screening using the refined NOP active-state models from the enrichment
analysis. Determination of the NOP receptor binding affinity of a
selected set of top-scoring hits resulted in identification of several
compounds with measurable binding affinity at the NOP receptor, one
of which had a new chemotype for NOP receptor binding. The hybrid
ligand-based and structure-based methodology demonstrates an effective
approach for virtual screening that leverages existing SAR and receptor
structure information for identifying novel hits for NOP receptor
binding. The refined active-state NOP homology models obtained from
the enrichment studies can be further used for structure-based optimization
of these new chemotypes to obtain potent and selective NOP receptor
ligands for therapeutic development.