As
the amount of data generated by biomolecular simulations dramatically
increases, new tools need to be developed to help manage this data
at the individual investigator or small research group level. In this
paper, we introduce iBIOMES Lite, a lightweight tool for biomolecular
simulation data indexing and summarization. The main goal of iBIOMES
Lite is to provide a simple interface to summarize computational experiments
in a setting where the user might have limited privileges and limited
access to IT resources. A command-line interface allows the user to
summarize, publish, and search local simulation data sets. Published
data sets are accessible via static hypertext markup language (HTML)
pages that summarize the simulation protocols and also display data
analysis graphically. The publication process is customized via extensible
markup language (XML) descriptors while the HTML summary template
is customized through extensible stylesheet language (XSL). iBIOMES
Lite was tested on different platforms and at several national computing
centers using various data sets generated through classical and quantum
molecular dynamics, quantum chemistry, and QM/MM. The associated parsers
currently support AMBER, GROMACS, Gaussian, and NWChem data set publication.
The code is available at 