Virus-like particles
(VLPs) have been created from luminescent
Pt(II) complex amphiphiles, able to form supramolecular structures
in water solutions, that can be encapsulated or act as templates of
cowpea chlorotic mottle virus capsid proteins. By virtue of a bottom-up
molecular design, icosahedral and nonicosahedral (rod-like) VLPs have
been constructed through diverse pathways, and a relationship between
the molecular structure of the complexes and the shape and size of
the VLPs has been observed. A deep insight into the mechanism for
the templated formation of the differently shaped VLPs was achieved,
by electron microscopy measurements (TEM and STEM) and bulk analysis
(FPLC, DLS, photophysical investigations). Interestingly, the obtained
VLPs can be visualized by their intense emission at room temperature,
generated by the self-assembly of the Pt(II) complexes. The encapsulation
of the luminescent species is further verified by their higher emission
quantum yields inside the VLPs, which is due to the confinement effect
of the protein cage. These hybrid materials demonstrate the potential
of tailor-made supramolecular systems able to control the assembly
of biological building blocks.